// src/EventTypes.ts
export const EVENT_SYS_AUTHENTICATED_USER = 'EVENT_SYS_AUTHENTICATED_USER';
export const EVENT_AUTH_FAILED            = 'EVENT_AUTH_FAILED';
export const EVENT_SYS_FETCHED_USER_APPS  = 'EVENT_SYS_FETCHED_USER_APPS_';
export const EVENT_SYS_FETCHED_USER_TABLES= 'EVENT_SYS_FETCHED_USER_TABLES';

export const EVENT_USER_CLICKED_ON_APP    = 'EVENT_USER_CLICKED_ON_APP';
export const EVENT_USER_CLICKED_ON_TABLE  = 'EVENT_USER_CLICKED_ON_TABLE';
export const EVENT_USER_CLICKED_NEW_RECORD= 'EVENT_USER_CLICKED_NEW_RECORD';
export const EVENT_USER_CLICKED_RECORD    = 'EVENT_USER_CLICKED_RECORD';
export const EVENT_RECORD_LIST_UPDATED    = 'EVENT_RECORD_LIST_UPDATED';

