// src/EventTypes.ts
export const EVENT_SYS_AUTHENTICATED_USER = 'EVENT_SYS_AUTHENTICATED_USER';
export const EVENT_AUTH_FAILED            = 'EVENT_AUTH_FAILED';
export const EVENT_SYS_FETCHED_USER_APPS  = 'EVENT_SYS_FETCHED_USER_APPS_';
export const EVENT_SYS_FETCHED_USER_TABLES= 'EVENT_SYS_FETCHED_USER_TABLES';

export const EVENT_USER_CLICKED_ON_APP    = 'EVENT_USER_CLICKED_ON_APP';
export const EVENT_RECORD_LIST_UPDATED    = 'EVENT_RECORD_LIST_UPDATED';
export const EVENT_USER_CLICKED_NEW_RECORD_BUTTON    = 'EVENT_USER_CLICKED_NEW_RECORD_BUTTON';
export const EVENT_USER_CLICKED_RECORD_ROW= 'EVENT_USER_CLICKED_RECORD_ROW';

